using UnityEngine;

public class HexagonControl : MonoBehaviour
{
    public GravityCalculation gravityCalculation;
    public HexagonPattern hexagonPattern;
    public int n;
    public int status;
    public int tempstatus;
    // ฤฟ๏ฟฝ๏ฟฝ๏ฟฝ๏ฟฝืช๏ฟฝวถศฃ๏ฟฝึป๏ฟฝ๏ฟฝยผZ๏ฟฝแฃฉ
    private float targetZ;
    // ๏ฟฝ๏ฟฝ๏ฟฝ๏ฟฝ๏ฟฝ๏ฟฝืชฦฝ๏ฟฝ๏ฟฝ๏ฟฝ๏ฟฝ
    public float rotationSpeed = 5f;

    void Start()
    {
        // ๏ฟฝ๏ฟฝ๏ฟฝ๏ฟฝ๏ฟฝ๏ฟฝ๏ฟฝ๏ฟฝสฑ๏ฟฝ๏ฟฝสผ๏ฟฝ๏ฟฝn
        n = 0;
        // ๏ฟฝ๏ฟฝยผ๏ฟฝ๏ฟฝวฐZ๏ฟฝ๏ฟฝฤณ๏ฟฝสผึต
        targetZ = transform.eulerAngles.z;
        status = (int)(transform.eulerAngles.z + 0.01 - 30) / 60;
        tempstatus = status;
    }

    void Update()
    {
        if(!hexagonPattern.isFaded)
        {
            // ๏ฟฝ๏ฟฝA๏ฟฝ๏ฟฝ๏ฟฝ๏ฟฝสฑ๏ฟฝ๏ฟฝ๏ฟฝ๏ฟฝืช60๏ฟฝ๏ฟฝ
            if (Input.GetKeyDown(KeyCode.A))
            {
                targetZ -= 60f;
                tempstatus= (tempstatus + 5) % 6;
            }
            // ๏ฟฝ๏ฟฝD๏ฟฝ๏ฟฝหณสฑ๏ฟฝ๏ฟฝ๏ฟฝ๏ฟฝืช60๏ฟฝ๏ฟฝ
            if (Input.GetKeyDown(KeyCode.D))
            {
                targetZ += 60f;
                tempstatus = (tempstatus + 1) % 6;
            }
            // ๏ฟฝ๏ฟฝS๏ฟฝ๏ฟฝn๏ฟฝ๏ฟฝ1
            if (Input.GetKeyDown(KeyCode.S))
            {
                n++;
                status = tempstatus;
                gravityCalculation.gravityCalculation();
            }

            // สน๏ฟฝ๏ฟฝLerpAngleสต๏ฟฝ๏ฟฝฦฝ๏ฟฝ๏ฟฝ๏ฟฝ๏ฟฝืช
            Vector3 currentAngles = transform.eulerAngles;
            currentAngles.z = Mathf.LerpAngle(currentAngles.z, targetZ, Time.deltaTime * rotationSpeed);
            transform.eulerAngles = currentAngles;
        }
        
    }

    void OnGUI()
    {
        // ๏ฟฝ๏ฟฝ๏ฟฝ๏ฟฝ๏ฟฝ๏ฟฝ๏ฟฝ๏ฟฝ๏ฟฝ๏ฟฝสพn๏ฟฝ๏ฟฝึต
        GUIStyle style = new GUIStyle(GUI.skin.label);
        style.fontSize = 36;

        GUI.Label(new Rect(10, 10, 300, 60), "๏ฟฝ๏ฟฝ๏ฟฝ๏ฟฝ๏ฟฝ๏ฟฝ๏ฟฝ๏ฟฝ๏ฟฝ" + n, style);
    }
}
